# Generated by Django 5.0.6 on 2025-02-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
