# Generated by Django 5.0.6 on 2025-03-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delivery_remove_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
