# Generated by Django 5.0.6 on 2025-03-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_cart_order_remove_order_cart_items_order_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='county',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
