# Generated by Django 5.0.6 on 2025-03-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(auto_created=True, default='', primary_key=True, serialize=False),
        ),
    ]
